const lang = {
    en: {
      search: "Search",
      gptSearchPlaceholder: "What would you like to watch today?",
      searchPlaceholder: "Search movies...",
      nowPlaying: "Now Playing",
      popular: "Popular",
      topRated: "Top Rated",
      upcoming: "Upcoming",
      signOut: "Sign Out",
      signIn: "Sign In",
      signUp: "Sign Up",
      fullName: "Full Name",
      email: "Email Address",
      password: "Password",
      forgotPassword: "Forgot Password?",
      noAccount: "New to FilmOracle?",
      alreadyAccount: "Already have an account?",
      signUpNow: "Sign up now",
      signInNow: "Sign in",
      welcomeBack: "Welcome Back",
      joinNow: "Join FilmOracle",
      signInSubtitle: "Sign in to continue your cinematic journey",
      signUpSubtitle: "Create an account for personalized recommendations",
      passwordHint: "Must be at least 6 characters",
      processing: "Processing...",
      demoInfo: "Demo: Use ubanto@gmail.com / Ubanto1234@",
      termsText: "By signing in, you agree to our Terms of Service and Privacy Policy",
      poweredBy: "Powered by AI • Results may vary • Click any movie for details",
      footerTagline: "Let AI guide you to your next favorite film"
    },
    hindi: {
      search: "खोजें",
      gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
      searchPlaceholder: "फिल्में खोजें...",
      nowPlaying: "अब चल रही है",
      popular: "लोकप्रिय",
      topRated: "टॉप रेटेड",
      upcoming: "आने वाली",
      signOut: "साइन आउट",
      signIn: "साइन इन",
      signUp: "साइन अप",
      fullName: "पूरा नाम",
      email: "ईमेल पता",
      password: "पासवर्ड",
      forgotPassword: "पासवर्ड भूल गए?",
      noAccount: "FilmOracle पर नए हैं?",
      alreadyAccount: "पहले से खाता है?",
      signUpNow: "अभी साइन अप करें",
      signInNow: "साइन इन करें",
      welcomeBack: "वापसी पर स्वागत है",
      joinNow: "FilmOracle से जुड़ें",
      signInSubtitle: "अपनी सिनेमाई यात्रा जारी रखने के लिए साइन इन करें",
      signUpSubtitle: "व्यक्तिगत अनुशंसाओं के लिए खाता बनाएं",
      passwordHint: "कम से कम 6 अक्षर होने चाहिए",
      processing: "प्रोसेस हो रहा है...",
      demoInfo: "डेमो: ubanto@gmail.com / Ubanto1234@ का उपयोग करें",
      termsText: "साइन इन करके, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत हैं",
      poweredBy: "एआई द्वारा संचालित • परिणाम भिन्न हो सकते हैं • विवरण के लिए किसी भी फिल्म पर क्लिक करें",
      footerTagline: "एआई को अपनी अगली पसंदीदा फिल्म खोजने में मार्गदर्शन करने दें"
    },
    punjabi: {
      search: "ਖੋਜ",
      gptSearchPlaceholder: "ਅੱਜ ਤੁਸੀਂ ਕੀ ਦੇਖਣਾ ਪਸੰਦ ਕਰੋਗੇ?",
      searchPlaceholder: "ਫਿਲਮਾਂ ਖੋਜੋ...",
      nowPlaying: "ਹੁਣ ਚੱਲ ਰਹੀਆਂ",
      popular: "ਮਸ਼ਹੂਰ",
      topRated: "ਚੋਟੀ ਦੀ ਰੇਟਿੰਗ",
      upcoming: "ਆਉਣ ਵਾਲੀਆਂ",
      signOut: "ਸਾਈਨ ਆਉਟ",
      signIn: "ਸਾਈਨ ਇਨ",
      signUp: "ਸਾਈਨ ਅੱਪ",
      fullName: "ਪੂਰਾ ਨਾਮ",
      email: "ਈਮੇਲ ਪਤਾ",
      password: "ਪਾਸਵਰਡ",
      forgotPassword: "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?",
      noAccount: "FilmOracle 'ਤੇ ਨਵੇਂ ਹੋ?",
      alreadyAccount: "ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?",
      signUpNow: "ਹੁਣੇ ਸਾਈਨ ਅੱਪ ਕਰੋ",
      signInNow: "ਸਾਈਨ ਇਨ ਕਰੋ",
      welcomeBack: "ਵਾਪਸੀ 'ਤੇ ਜੀ ਆਇਆਂ ਨੂੰ",
      joinNow: "FilmOracle ਨਾਲ ਜੁੜੋ",
      signInSubtitle: "ਆਪਣੀ ਸਿਨੇਮਾਈ ਯਾਤਰਾ ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ",
      signUpSubtitle: "ਨਿੱਜੀ ਸਿਫ਼ਾਰਸ਼ਾਂ ਲਈ ਖਾਤਾ ਬਣਾਓ",
      passwordHint: "ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰ ਹੋਣੇ ਚਾਹੀਦੇ ਹਨ",
      processing: "ਪ੍ਰੋਸੈਸਿੰਗ...",
      demoInfo: "ਡੈਮੋ: ubanto@gmail.com / Ubanto1234@ ਦੀ ਵਰਤੋਂ ਕਰੋ",
      termsText: "ਸਾਈਨ ਇਨ ਕਰਕੇ, ਤੁਸੀਂ ਸਾਡੀਆਂ ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ ਅਤੇ ਗੋਪਨੀਯਤਾ ਨੀਤੀ ਨਾਲ ਸਹਿਮਤ ਹੁੰਦੇ ਹੋ",
      poweredBy: "AI ਦੁਆਰਾ ਸੰਚਾਲਿਤ • ਨਤੀਜੇ ਵੱਖ-ਵੱਖ ਹੋ ਸਕਦੇ ਹਨ • ਵੇਰਵਿਆਂ ਲਈ ਕਿਸੇ ਵੀ ਫਿਲਮ 'ਤੇ ਕਲਿੱਕ ਕਰੋ",
      footerTagline: "AI ਨੂੰ ਤੁਹਾਡੀ ਅਗਲੀ ਪਸੰਦੀਦਾ ਫਿਲਮ ਲੱਭਣ ਵਿੱਚ ਮਾਰਗਦਰਸ਼ਨ ਕਰਨ ਦਿਓ"
    },
    spanish: {
      search: "Buscar",
      gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
      searchPlaceholder: "Buscar películas...",
      nowPlaying: "Ahora en Cines",
      popular: "Populares",
      topRated: "Mejor Calificadas",
      upcoming: "Próximamente",
      signOut: "Cerrar Sesión",
      signIn: "Iniciar Sesión",
      signUp: "Registrarse",
      fullName: "Nombre Completo",
      email: "Correo Electrónico",
      password: "Contraseña",
      forgotPassword: "¿Olvidaste tu contraseña?",
      noAccount: "¿Nuevo en FilmOracle?",
      alreadyAccount: "¿Ya tienes una cuenta?",
      signUpNow: "Regístrate ahora",
      signInNow: "Iniciar Sesión",
      welcomeBack: "Bienvenido de Nuevo",
      joinNow: "Únete a FilmOracle",
      signInSubtitle: "Inicia sesión para continuar tu viaje cinematográfico",
      signUpSubtitle: "Crea una cuenta para recomendaciones personalizadas",
      passwordHint: "Debe tener al menos 6 caracteres",
      processing: "Procesando...",
      demoInfo: "Demo: Usa ubanto@gmail.com / Ubanto1234@",
      termsText: "Al iniciar sesión, aceptas nuestros Términos de Servicio y Política de Privacidad",
      poweredBy: "Impulsado por IA • Los resultados pueden variar • Haz clic en cualquier película para ver detalles",
      footerTagline: "Deja que la IA te guíe hacia tu próxima película favorita"
    }
  };
  
  export default lang;